### ISSUE TITLE
ElasticSearch Experiments

### ISSUE THREAD

**Issue by tux4** [Code4Nepal/akshara-project#5]
We need to explore the features of elastic search, and how it will work with our use case.

### Outcomes

1. Devanagari search quality tests

    - Figure out the state of art practices.

2. Transliterated Search

    - While indexing devanagari text, we will also store them as the transliterated latin text. This will allow users to search using latin script. Investigate the most performant way of doing this.

**Comment by anupdhml** [comment]
@tux4 @ijesh submitted pull request #13 with the setup so far.

We need to improve the search quality more (eg: with Nepali-specific stemming), but for now, what we have should be good enough.

Future steps: https://github.com/Code4Nepal/akshara-project/tree/es_akshara/elasticsearch#todo

**Comment by anupdhml** [comment]
Filed #15 with some updates -- that is the setup running in our shared dev.

**Comment by tux4** [comment]
यो बन्द गर्दा हुन्छ ?

**Comment by anupdhml** [comment]
@tux4 हुन्छ
