### ISSUE TITLE
Autocomplete suggestions acting weird

### ISSUE THREAD

**Issue by spaudel** [Code4Nepal/akshara-project#61]
When you select the first suggestion from autocomplete. And then redo the search with other suggestions the search reverts back to the first suggestion.

Reproduction steps: Type an author's name in Nepali. Autocomplete gives suggestions of titles. Select the first title, hit enter. Once the results get displayed, click on the search box and select other suggestions. Hit enter.

UI bug

**Comment by aishraj** [comment]
Related to #65

**Comment by tux4** [comment]
Fixed in development
