### ISSUE TITLE
Hosting and infrastructure decisions

### ISSUE THREAD

**Issue by tux4** [Code4Nepal/akshara-project#8]
We need to determine the infrastructure where we host our app

# Outcomes

- Cloud hosting space that is fast globally but specifically in Nepal
- Domain name purchased in our name

**Comment by ravinepal** [comment]
hi all - i just spoke with @spaudel. I mentioned to her that @codefornepal can possibly apply to get non-profit credit from AWS and help ensure the cost of the hosting space is low/managable. 

Also, when you all decide domain and would like Code for Nepal can help buy that too
